default_agent: mbti_travel_planner_agent
agents:
  mbti_travel_planner_agent:
    name: mbti_travel_planner_agent
    entrypoint: C:/MBTI_Travel_Assistant/mbti-travel-planner-agent/main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '209803798463'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: mbti_travel_planner_agent-JPTzWT3IZp
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:209803798463:runtime/mbti_travel_planner_agent-JPTzWT3IZp
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
