default_agent: restaurant_reasoning_mcp
agents:
  restaurant_reasoning_mcp:
    name: restaurant_reasoning_mcp
    entrypoint: C:/MBTI_Travel_Assistant/restaurant-search-result-reasoning-mcp/restaurant_reasoning_mcp_server.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '209803798463'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: restaurant_reasoning_mcp-UFz1VQCFu1
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:209803798463:runtime/restaurant_reasoning_mcp-UFz1VQCFu1
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: restaurant_search_conversational_agent_mem-YbRhxj54Yd
      memory_arn: null
      memory_name: restaurant_reasoning_mcp_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1ofgeckef3po4i3us4j1m4chvd
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KePRX24Bn/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
