default_agent: restaurant_search_result_reasoning_agent
agents:
  restaurant_search_result_reasoning_agent:
    name: restaurant_search_result_reasoning_agent
    entrypoint: C:/MBTI_Travel_Assistant/restaurant-search-result-reasoning-mcp/restaurant_reasoning_mcp_server.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::209803798463:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-86b9d22e10
      execution_role_auto_create: false
      account: '209803798463'
      region: us-east-1
      ecr_repository: 209803798463.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-restaurant_search_result_reasoning_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: restaurant_search_result_reasoning_agent-MSns5D6SLE
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:209803798463:runtime/restaurant_search_result_reasoning_agent-MSns5D6SLE
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-restaurant_search_result_reasoning_agent-builder
      execution_role: arn:aws:iam::209803798463:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-86b9d22e10
      source_bucket: bedrock-agentcore-codebuild-sources-209803798463-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: restaurant_search_result_reasoning_agent_mem-Qx7aMVDx42
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:209803798463:memory/restaurant_search_result_reasoning_agent_mem-Qx7aMVDx42
      memory_name: restaurant_search_result_reasoning_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1ofgeckef3po4i3us4j1m4chvd
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KePRX24Bn/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
