system_name: enhanced-mcp-status-check-production
version: 1.0.0
dual_monitoring_enabled: true

mcp_health_checks:
  enabled: true
  default_timeout_seconds: 15
  default_retry_attempts: 5
  tools_list_validation: true
  expected_tools_validation: true
  default_expected_tools:
    - search_restaurants_by_district
    - recommend_restaurants
    - analyze_restaurant_sentiment
  request_timeout_ms: 45000
  connection_pool_size: 20
  jwt_auth_enabled: true
  jwt_discovery_url: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KePRX24Bn/.well-known/openid-configuration"
  jwt_audience: "1ofgeckef3po4i3us4j1m4chvd"

rest_health_checks:
  enabled: true
  default_timeout_seconds: 12
  default_retry_attempts: 3
  health_endpoint_path: "/status/health"
  metrics_endpoint_path: "/status/metrics"
  expected_status_codes: [200, 201, 202]
  retry_backoff_factor: 2.0
  max_retry_delay_seconds: 60
  connection_pool_size: 30
  validate_response_format: true
  required_health_fields: ["status", "timestamp"]
  auth_type: "bearer"
  auth_header_name: "Authorization"

result_aggregation:
  mcp_priority_weight: 0.7
  rest_priority_weight: 0.3
  require_both_success_for_healthy: true
  degraded_on_single_failure: true
  health_score_calculation: "weighted_average"
  failure_threshold: 0.3
  degraded_threshold: 0.6

circuit_breaker:
  enabled: true
  failure_threshold: 3
  recovery_timeout_seconds: 120
  half_open_max_calls: 5
  mcp_circuit_breaker_enabled: true
  rest_circuit_breaker_enabled: true
  independent_circuit_breakers: true

monitoring:
  enabled: true
  metrics_collection_enabled: true
  health_check_interval_seconds: 15
  metrics_retention_hours: 72
  concurrent_health_checks: true
  max_concurrent_checks: 20

servers:
  - server_name: restaurant-search-mcp-prod
    mcp_endpoint_url: "https://restaurant-search.example.com/mcp"
    rest_health_endpoint_url: "https://restaurant-search.example.com/status/health"
    mcp_enabled: true
    rest_enabled: true
    mcp_timeout_seconds: 15
    rest_timeout_seconds: 12
    mcp_expected_tools:
      - search_restaurants_by_district
      - search_restaurants_by_meal_type
      - search_restaurants_combined
    mcp_retry_attempts: 5
    rest_retry_attempts: 3
    jwt_token: null
    auth_headers:
      X-API-Key: "${API_KEY}"
    mcp_priority_weight: 0.7
    rest_priority_weight: 0.3
    require_both_success: true

  - server_name: restaurant-reasoning-mcp-prod
    mcp_endpoint_url: "https://restaurant-reasoning.example.com/mcp"
    rest_health_endpoint_url: "https://restaurant-reasoning.example.com/status/health"
    mcp_enabled: true
    rest_enabled: true
    mcp_timeout_seconds: 20
    rest_timeout_seconds: 15
    mcp_expected_tools:
      - recommend_restaurants
      - analyze_restaurant_sentiment
    mcp_retry_attempts: 5
    rest_retry_attempts: 3
    jwt_token: null
    auth_headers:
      X-API-Key: "${API_KEY}"
    mcp_priority_weight: 0.8
    rest_priority_weight: 0.2
    require_both_success: true

  - server_name: mbti-travel-assistant-mcp-prod
    mcp_endpoint_url: "https://mbti-travel.example.com/mcp"
    rest_health_endpoint_url: "https://mbti-travel.example.com/status/health"
    mcp_enabled: true
    rest_enabled: true
    mcp_timeout_seconds: 25
    rest_timeout_seconds: 20
    mcp_expected_tools:
      - search_restaurants_by_district
      - recommend_restaurants
      - analyze_restaurant_sentiment
      - get_mbti_attractions
    mcp_retry_attempts: 5
    rest_retry_attempts: 3
    jwt_token: null
    auth_headers:
      X-API-Key: "${API_KEY}"
    mcp_priority_weight: 0.6
    rest_priority_weight: 0.4
    require_both_success: false